// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcWDn8qyuVSbAfJEKmxU4CWGo8tA9AW58',
    appId: '1:1077809354673:web:e26d8c5e2ab8e5cc2ecf90',
    messagingSenderId: '1077809354673',
    projectId: 'studentattendancesystem-ab5ff',
    authDomain: 'studentattendancesystem-ab5ff.firebaseapp.com',
    storageBucket: 'studentattendancesystem-ab5ff.firebasestorage.app',
    measurementId: 'G-C5T56XXH47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGa4Pyqs8-1iwsTx1NIpDeegNBqZpe6YQ',
    appId: '1:1077809354673:android:79a0aec851eed60d2ecf90',
    messagingSenderId: '1077809354673',
    projectId: 'studentattendancesystem-ab5ff',
    storageBucket: 'studentattendancesystem-ab5ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSOPBaZmrulBCUcQlvtTT-CShLNRzb_-U',
    appId: '1:1077809354673:ios:0ea82f7f479302d32ecf90',
    messagingSenderId: '1077809354673',
    projectId: 'studentattendancesystem-ab5ff',
    storageBucket: 'studentattendancesystem-ab5ff.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSOPBaZmrulBCUcQlvtTT-CShLNRzb_-U',
    appId: '1:1077809354673:ios:0ea82f7f479302d32ecf90',
    messagingSenderId: '1077809354673',
    projectId: 'studentattendancesystem-ab5ff',
    storageBucket: 'studentattendancesystem-ab5ff.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcWDn8qyuVSbAfJEKmxU4CWGo8tA9AW58',
    appId: '1:1077809354673:web:c614f31f31c8362f2ecf90',
    messagingSenderId: '1077809354673',
    projectId: 'studentattendancesystem-ab5ff',
    authDomain: 'studentattendancesystem-ab5ff.firebaseapp.com',
    storageBucket: 'studentattendancesystem-ab5ff.firebasestorage.app',
    measurementId: 'G-ED1F967HCS',
  );
}
